// Code generated by mockery v2.14.0. DO NOT EDIT.

package sp

import mock "github.com/stretchr/testify/mock"

// MockVariable is an autogenerated mock type for the Variable type
type MockVariable struct {
	mock.Mock
}

type mockConstructorTestingTNewMockVariable interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockVariable creates a new instance of MockVariable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockVariable(t mockConstructorTestingTNewMockVariable) *MockVariable {
	mock := &MockVariable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
