name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1' 
      - name: Test and build
        run: make
      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: |
            bin